### ISSUE TITLE
Publish to the GH Marketplace

### ISSUE THREAD

**Issue by ravwojdyla** [related-sciences/gce-github-runner#1]
@eric-czech I might need your help please, to publish this action to the GH Marketplace we need:

> related-sciences must accept the GitHub Marketplace Developer Agreement. Contact an org admin to accept it.

Do you have those powers?

**Comment by eric-czech** [comment]
Hmm taking a look now

**Comment by ravwojdyla** [comment]
Published at: https://github.com/marketplace/actions/ephemeral-gce-github-self-hosted-runner
