### ISSUE TITLE
GCE VM not being deleted during a test run

### ISSUE THREAD

**Issue by andycockers** [related-sciences/gce-github-runner#11]
![Screenshot from 2021-10-13 17-55-31](https://user-images.githubusercontent.com/34304883/137178876-2fd560b8-1df5-44c0-a919-929b5d0c9ca8.png)

The Runner remains connected and the VM is not deleted. 

In the code, in action.sh line 201:

`echo "sleep ${shutdown_timeout}; gcloud --quiet compute instances delete $NAME --zone=$ZONE" | env -i at now`

This does not appear to be running.

**Comment by ravwojdyla** [comment]
👋 @andycockers sorry missed this issue, do you remember which OS did you use for you runners, does it have `at`? Did you see any errors in the GCP logging (maybe the VM doesn't have the rights to self-destroy?)?
