### ISSUE TITLE
Should `ephemeral` be `true` by default?

### ISSUE THREAD

**Issue by ravwojdyla** [related-sciences/gce-github-runner#18]
https://github.com/related-sciences/gce-github-runner/pull/13#discussion_r796021462 should this be `true` by default?

_Originally posted by @ravwojdyla in https://github.com/related-sciences/gce-github-runner/pull/16#discussion_r796052442_

**Comment by Manouchehri** [comment]
We're running multiple jobs in a single workflow/action, and from what I understand, setting this flag would break that.

**Comment by ravwojdyla** [comment]
@Manouchehri ah, I see, let's keep it as it is right now then.
