### ISSUE TITLE
Can we self-shutdown if/when the Actions Runner is ephemeral?

### ISSUE THREAD

**Issue by ravwojdyla** [related-sciences/gce-github-runner#29]
https://github.com/related-sciences/gce-github-runner/pull/16 added the ephemeral flag, if that is the case, can we self shutdown then/if the Actions Runner exits?

**Comment by everpeace** [comment]
> if that is the case, can we self shutdown then/if the Actions Runner exits?

Yes, I confirmed the behavior in my project. I think [`ACTIONS_RUNNER_HOOK_JOB_COMPLETED`](https://github.com/related-sciences/gce-github-runner/blob/main/action.sh#L224) works as expected. After the test is completed (no matter it succeded/failed/canceled), VM instance was deleted.

As you might noticed, workflow was failed/canceled before the runner fetching a job, VM will keep running, so we need to handle to delete it manually as described [here](https://github.com/related-sciences/gce-github-runner/issues/10#issuecomment-1367933237).

**Comment by ravwojdyla** [comment]
@everpeace right, I think this can actually be closed given the job completed hook was implemented via #34
