### ISSUE TITLE
jq command not found

### ISSUE THREAD

**Issue by dhimmel** [related-sciences/gce-github-runner#38]
I got the following [error](https://github.com/related-sciences/nxontology-data/actions/runs/6097827937/job/16546330801):

```
/actions-runner/_work/_actions/related-sciences/gce-github-runner/main/action.sh: line 175: jq: command not found
(23) Failed writing body
```

Should `related-sciences/gce-github-runner` be responsible for installing jq or is that up to the workflow using it?

**Comment by dhimmel** [comment]
Here is where jq is called first:

https://github.com/related-sciences/gce-github-runner/blob/6cb6998237b68764579d45dde1dabd94fa494f47/action.sh#L172-L176

**Comment by ravwojdyla** [comment]
@dhimmel sorry for the delay. In your error example above, that error happened during the on-the-GCE-VM shutdown hook, which we no longer use as per #34. I can see ([code](https://github.com/related-sciences/nxontology-data/blob/c7b14299b18ed391762758bf76d8f5f806006a60/.github/workflows/create.yaml)) that nxonto-date doesn't use explicit shutdown hook anymore 👏- so I don't think this will be an issue anymore.

The cases when `jq` is still used at the moment are all on the GitHub-hosted Action runner, this is the code that creates and deletes the GCE VM, and according to the GitHub documentation for `ubuntu-latest`, `jq` is preinstalled: https://github.com/actions/runner-images/blob/7704a85e7f0a0dcab94608297f5bf99266f098dd/images/linux/Ubuntu2204-Readme.md

Closing, please reopen if the error persists.
